//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuongMaiDienTu_v1._0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_role
    {
        public int Account_role_id { get; set; }
        public string Account_role_name { get; set; }
    }
}
