//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code_NhapSanPham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int Image_id { get; set; }
        public int SanPham_id { get; set; }
        public string Image1 { get; set; }
        public Nullable<bool> key { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
