//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code_NhapSanPham.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.Images = new HashSet<Image>();
        }
    
        public int SanPham_id { get; set; }
        public string SanPham_description { get; set; }
        public string SanPham_name { get; set; }
        public Nullable<double> SanPham_price { get; set; }
        public Nullable<double> SanPham_pirceSale { get; set; }
        public int Type_SanPham_id { get; set; }
        public Nullable<bool> Sale_key { get; set; }
        public string img { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [NotMapped]
        public HttpPostedFileBase imageUploader { get; set; }
        public virtual ICollection<Image> Images { get; set; }
        public virtual Type_SanPham Type_SanPham { get; set; }
    }
}
