//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuongMaiDienTu_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPhamDetail
    {
        public int SanPhamDetail_id { get; set; }
        public Nullable<int> SanPham_id { get; set; }
        public Nullable<int> Size_id { get; set; }
        public Nullable<int> Soluong { get; set; }
    
        public virtual SanPham SanPham { get; set; }
        public virtual Size Size { get; set; }
    }
}
