//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuongMaiDienTu_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int Account_id { get; set; }
        public string Account_user { get; set; }
        public string Account_password { get; set; }
        public int Account_role_id { get; set; }
        public int Infor_id { get; set; }
        public string LichSuMuaHang { get; set; }
    }
}
